engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true

ratings:
   paths:
   - index.js

exclude_paths:
- test.js
